### PR TITLE
Dont generate base snapshot if already exists

### PR DESCRIPTION
**Pull request by bpetetot**
Hi, this PR is related to my issue #34

## The problem

I tried to find a good solution to avoid override existing snapshots when running `npm run --env type=base`. I would like to generate base snapshots of the new tests or new test cases only and to avoid specifying my `testFiles` to the `npm run --env type=base` command.

## The solution

Before making a screenshot for a base snapshot, it checks if the snapshot already exists. So if the snapshot exists, the screenshot is not taken, else it is.

So the actual behaviour remains the same, when you run
```
cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base
```

But if you add `trashAssetsBeforeRuns=false` to the command, then base snapshots are not deleted, so only the new ones are generated:
```
cypress run --env type=base --config screenshotsFolder=cypress/snapshots/base,trashAssetsBeforeRuns=false
```
And if you want to update one specific snapshot, you just have to delete it from the `snapshot/base` folder and execute the previous command.

What do you think about it ?

Thanks again for the project ;)

### CODE REVIEW

**Comment by mjhea0** [comment]
I like this idea.

Two things:

- Would you be able to update the README, indicating how to use `trashAssetsBeforeRuns`?
- I'd love to see either some Jest or Cypress tests that cover this new functionality

**Comment by bpetetot** [comment]
Thanks, 
No problem, I will update the README and add some tests

**Comment by gabbersepp** [comment]
are there any plans to finish this PR?

**Comment by mjhea0** [comment]
@bpetetot ^^^

**Comment by mjhea0** [comment]
@gabbersepp or @TimKolberger - Do either of you want to add some tests for this one?

**Comment by mattbrailsford** [comment]
Just another vote for this PR to be merged 👍

**Comment by bpetetot** [comment]
Sorry I missed the previous notification and forgot the PR.
I'm going to rebase it and add some tests ASAP.

**Comment by gsnunes** [comment]
Just more one vote for this PR to be merged

**Comment by mjhea0** [comment]
Closing this PR due to lack of activity. Feel free to reopen with some tests.

**Pull request closed without merging**
