### PR TITLE
fix: save diff images only on failed tests

### PR DESCRIPTION
**Pull request by Zaista**
Resolves: #108

### CODE REVIEW

**Comment by Zaista** [comment]
@mjhea0 could you please review and approve the workflow?

**Comment by mjhea0** [comment]
@Zaista - thanks for the PR!

So, this implementation only saves the diff image on failed tests by default, correct? Can you please make this configurable?

**Comment by Zaista** [comment]
Correct. I thought about it, but honestly I do not see the point of making this configurable. Why would anyone need this pic? You anyway have the actual screenshot...

**Comment by mjhea0** [comment]
I'm not sure, but this changes the behavior so I'd like it to be configurable in case someone is dependent on it.

**Comment by Zaista** [comment]
@mjhea0 done

**Comment by clmntrss** [comment]
@mjhea0 could you take a look on this PR please ?

**Comment by Zaista** [comment]
The fact this simple PR takes half a year is disturbing.

**Comment by mjhea0** [comment]
I'm slammed and don't use this project anymore. If you'd like to step up and become a maintainer, then go for it, @Zaista.

**Comment by Zaista** [comment]
Yep, let's do it. I'll give it a go

**Comment by mjhea0** [comment]
I just added you as a collaborator. Let's start there.

**Pull request merged**
