### PR TITLE
Add silent=true option

### LINKED ISSUE #7: Add a silent option for debugging mode
This will allow to have better worflow while writting tests.

for instance
```
--env silent=true
```

### PR DESCRIPTION
**Pull request by j1348**
close #7

### CODE REVIEW

**Comment by mjhea0** [comment]
I guess I don't fully understand this. You want to bypass the actual image diff'ing?

**Comment by j1348** [comment]
I had encountered problems because I define in `"screenshotsFolder":"cypress/snapshots/"`

**Comment by mjhea0** [comment]
Yes, that makes sense. Sounds like you still want the diff'ing to occur--you just don't want the test run to fail if a single test fails?

For example:

```javascript
/* eslint-disable no-undef */

function compareSnapshotCommand() {
  Cypress.Commands.add('compareSnapshot', (name, errorThreshold = 0.0) => {

    // get image title from the 'type' environment variable
    let title = 'actual';
    if (Cypress.env('type') === 'base') {
      title = 'base';
    }

    // take snapshot
    cy.screenshot(`${name}-${title}`);

    // run visual tests
    if (Cypress.env('type') === 'actual') {
      const options = {
        fileName: name,
        specDirectory: Cypress.spec.name,
      };
      cy.task('compareSnapshotsPlugin', options).then((results) => {
        if (results.percentage > errorThreshold) {
          const message = `${name} images are different`;
          // UPDATES
          if (Cypress.env('silent') === 'true') {
            console.log(message);
          } else {
            throw new Error(message);
          }
        }
      });
    }
  });
}

/* eslint-enable no-undef */

module.exports = compareSnapshotCommand;
```

**Comment by j1348** [comment]
@mjhea0 it makes sens with your implementation.

**Comment by mjhea0** [comment]
Alright. We still need to update the docs and the tests in the PR. Want to give it a try?

**Pull request closed without merging**
