### PR TITLE
add posibility to configure paths by env

### LINKED ISSUE #48: Make directories configurable
I don't like the way how the snapshotdirectories are used.

I want to have a folder **cypress/screenshots** and a folder **cypress/snapshots/base**. I introduced the possibility to configure it by "env" property in cypress.json

### PR DESCRIPTION
**Pull request by gabbersepp**
fixes #48

### CODE REVIEW

**Comment by gabbersepp** [comment]
I tried to pass the config in an own section in cypress.json but this did not work. Custom properties in cypress.json did not appear in the **config** object in the plugin initializing. So I've choosen the **env**. I did not write it very clean. Please tell me, if this solution can be merged and I will try to make the code a bit better :-)

**Comment by mjhea0** [comment]
@gabbersepp yes, I think this is a good idea. Want to clean up the code, add some tests, and update the README?

**Comment by gabbersepp** [comment]
> @gabbersepp yes, I think this is a good idea. Want to clean up the code, add some tests, and update the README?

Hi, yes I will do this :-)

**Comment by gabbersepp** [comment]
@mjhea0 I think everything must be fine now. But unfortunatelly two tests are failing because of the threshold is exceeded. Maybe you can have a look at it?
And I have not added an extra test because just by setting the options in cypress.json the whole logic is already tested. Is this enough?

**Comment by gabbersepp** [comment]
@mjhea0 I try to fix the last failing error. The problem is, that the command "compareSnapshotTest" takes the screenshot itself and does not rely on the logic of the plugin. This breaks the tests, because the task which copies the screenshot from "screenshots" into "snapshots/base" is not called. I revert the path settings so it is the same as before my commit. Additionally I added tests that play with the environment variables.

**Comment by gabbersepp** [comment]
@mjhea0 Yes, everything green :-)

**Pull request merged**
