### PR TITLE
serialize a error object with socket communication.

### LINKED ISSUE #84: Intermittent Error: [object Object] on compareSnapshot command
image
All test in this screenshot are using Cypress visual regression to compare snapshot. Some of them pass and some fail because of the object Object error. 

Does someone know how to fix this? I don't know what more details are relevant to be share. But please let me know if anything else is required.

### PR DESCRIPTION
**Pull request by MSakamaki**
fix #84

### CODE REVIEW

**Comment by mjhea0** [comment]
Any chance you'd be able to add some tests for this?

**Comment by MSakamaki** [comment]
I get it!
As an addition to the docker tests, I challenge to test for error bubble-up!

**Comment by MSakamaki** [comment]
@mjhea0 I have added a test that can catch error bobble ups in cypress docker.
(updated the case of missing files)

do you have any suggestions for test cases I should add other than this one?

**Comment by mjhea0** [comment]
Looks great! I'd like to try to get a few for folks to look at it.

@PeterDekkers, @Krismix1, @tdikarim, @vineetbrikl, @azz0r, @adrienlucas - any thoughts on the PR?

**Comment by Krismix1** [comment]
No objections from my side. Tested the new version in my project, and it worked.

**Comment by PeterDekkers** [comment]
These changes look good to me. I haven't tested the code, though. Thanks!

**Pull request merged**
