### PR TITLE
fixing mkdirp arguments

### PR DESCRIPTION
**Pull request by srikanthkyatham**
I have got error when trying to use the package.
Seems the mkdirp arguments were illegal

I have made the functions async, hope its clearer

### CODE REVIEW

**Comment by mjhea0** [comment]
Thanks for the PR, @srikanthkyatham! Just wanted to let you know that I've seen it and I should have time in the next few days to review. 

I've been thinking about replacing [mkdirp](https://www.npmjs.com/package/mkdirp) with [fs.mkdir](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_mkdir_path_options_callback) with the `recursive` option as `true`. Any thoughts? Now might be a good time to make that move.

**Comment by srikanthkyatham** [comment]
I can check it and update the pr

**Comment by srikanthkyatham** [comment]
Hi mjhea0,

seems the recursive option is supported in 

> v10.12.0 | The second argument can now be an options object with recursive and mode 
properties.

If choose this option it would mean node 8 would be broken. How do you wish to handle it.

**Comment by mjhea0** [comment]
We should probably drop 8 since it's no longer being maintained. 

https://nodejs.org/en/about/releases/

Agreed?

**Comment by srikanthkyatham** [comment]
Agreed. We should drop the node 8

**Comment by srikanthkyatham** [comment]
Open question, how do you wish to handle the cases where creation of folders fail?
Option
1. throw an error
2. ignore the failure and proceed with execution

**Comment by mjhea0** [comment]
Could you make it configurable with a `fail_silently` variable?

- Default value is `true` so it will log the error to console and execution will proceed. 
- Allow the end user to override this by setting a config variable in *cypress.json*.

How does that sound?

**Comment by mariya-gfx** [comment]
@srikanthkyatham, your fix works. Just tried it, see #26 for reference

**Comment by mjhea0** [comment]
@srikanthkyatham this looks good. any more changes?

**Comment by srikanthkyatham** [comment]
@mjhea0 no I that's about it.

**Comment by mariya-gfx** [comment]
@mjhea0, @srikanthkyatham, can you please review #26? Thanks.

**Comment by mjhea0** [comment]
Released! https://www.npmjs.com/package/cypress-visual-regression

Thanks for your help. Much appreciated.

**Pull request merged**
