### PR TITLE
TypeScript: Update docs, Add type for plugin

### PR DESCRIPTION
**Pull request by karlhorky**
Hi @mjhea0, thanks for this package!

Just updating the TS docs and types to allow for full TypeScript usage, also in `cypress/plugins/index.ts`

### CODE REVIEW

**Comment by karlhorky** [comment]
@mjhea0 added bbf9f01447671329782473deca07ae8869ec5160 to try to address the ESLint error:

```
> cypress-visual-regression@1.6.0 lint /home/runner/work/cypress-visual-regression/cypress-visual-regression
> eslint src/**

...

/home/runner/work/cypress-visual-regression/cypress-visual-regression/src/plugin.d.ts
  1:9  error  Parsing error: Unexpected token function

✖ 2 problems (1 error, 1 warning)
```

**Comment by mjhea0** [comment]
Sorry for the delay. Would you be able to address the merge conflict, @ karlhorky.

**Comment by EliRobinson** [comment]
@mjhea0 - Is this OK to merge, would love to see this fly!

**Comment by karlhorky** [comment]
@mjhea0 Thanks for the merge and releasing `cypress-visual-regression@1.6.3`!

**Comment by mjhea0** [comment]
For sure, @karlhorky. Thanks again!

**Pull request merged**
